'use strict';
window.CartUI = (()=>{
 const D=CartDesign,$=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const groups={power:'전원 · 보호',safety:'비상정지 · 재무장',drive:'차동 구동계',compute:'연산 · USB',sensor:'전방 센서',signal:'신호 인터페이스',steering:'전륜 조향'};
 const kinds={power:'구동 전력',steerpower:'12V 조향 전력',return:'0V 귀환',motor:'H브리지 출력',logic:'저전압 전원',safety:'안전정지',signal:'디지털 신호',usb:'USB / OEM 하네스',charge:'충전'};
 const colors={power:'#be5b3d',steerpower:'#d77a28',return:'#6f7d8a',motor:'#ac8839',logic:'#36866d',safety:'#7c7130',signal:'#647fc5',usb:'#8c75b5',charge:'#b8769c'};
 let timer,lastFocus;
 function toast(text){const el=$('#toast');el.textContent=text;el.classList.remove('hidden');clearTimeout(timer);timer=setTimeout(()=>el.classList.add('hidden'),4200);}
 function save(name,content,type='text/plain;charset=utf-8'){const blob=content instanceof Blob?content:new Blob([content],{type});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),15000)}
 function csv(rows){const q=v=>'"'+String(v??'').replaceAll('"','""')+'"';return '\ufeff'+rows.map(row=>row.map(q).join(',')).join('\r\n')}
 function connectionCSV(){const ks=Object.keys(D.connections[0]);save('Smart-Cart-D3-point-to-point.csv',csv([ks,...D.connections.map(w=>ks.map(k=>w[k]))]),'text/csv;charset=utf-8')}
 function closeModal(){const root=$('#modal-root');root.innerHTML='';document.body.style.overflow='';lastFocus?.focus?.()}
 function modal(title,body){lastFocus=document.activeElement;const root=$('#modal-root');root.innerHTML='<div class="modal-backdrop"><section class="modal" role="dialog" aria-modal="true" aria-label="'+esc(title)+'"><div class="modal-head"><h2>'+esc(title)+'</h2><button aria-label="닫기" id="modal-close">×</button></div>'+body+'</section></div>';document.body.style.overflow='hidden';$('#modal-close').onclick=closeModal;root.firstElementChild.onclick=e=>{if(e.target===e.currentTarget)closeModal()};$('#modal-close').focus()}
 function gates(){modal('통전 보류 조건 · 10개', '<p>웹 파일의 연결 검사는 전기적 안전 인증이 아닙니다. 실물 부품의 데이터시트·시험 결과·책임자 승인이 없으므로 아래 조건은 모두 HOLD입니다.</p>'+D.gates.map(g=>'<article class="gate"><div class="gate-id">'+esc(g.id)+' / HOLD</div><h3>'+esc(g.title)+'</h3><p>'+esc(g.why)+'</p><p class="required">해소 조건 · '+esc(g.required)+'</p></article>').join(''))}
 function sources(){modal('설계 근거와 원본 스냅샷','<p>3개 저장소의 공개 스냅샷과 제조사 자료를 대조했습니다. 제조사 자료는 특정 모듈을 무조건 승인한다는 의미가 아니며, 현재 설계 변경은 D3 문서에 구분했습니다.</p>'+D.sources.map(s=>'<div class="source"><code>'+esc(s.id)+'</code><a href="'+esc(s.url)+'" target="_blank" rel="noopener noreferrer">'+esc(s.title)+' ↗</a><small>'+esc(s.url)+'</small></div>').join(''))}
 function relatedHTML(wires){return '<div class="related">'+wires.map(w=>'<button class="chip" data-wire="'+esc(w.id)+'" title="'+esc(w.from+' → '+w.to)+'">'+esc(w.id)+'</button>').join('')+'</div>'}
 function bindRelated(callback){document.querySelectorAll('#inspector [data-wire]').forEach(b=>b.onclick=()=>callback(b.dataset.wire));}
 function inspect(id,mode='model',callback=()=>{}){
  const target=$('#inspector'),w=D.connections.find(w=>w.id===id),c=D.components.find(c=>c.id===id);
  if(w){target.innerHTML='<div class="eyebrow">HARNESS INSPECTOR / D3</div><div class="inspector-ref">'+esc(w.id)+'</div><h2>'+esc(kinds[w.kind])+'</h2><p class="subtitle mono">'+esc(w.net)+'</p><div class="divider"></div><div class="info-pair"><span>출발</span><strong class="mono">'+esc(w.from)+'</strong></div><div class="info-pair"><span>도착</span><strong class="mono">'+esc(w.to)+'</strong></div><div class="info-pair"><span>규격</span><strong>'+esc(w.gauge)+'</strong></div><p>'+esc(w.note||'실물 단자·극성·커넥터 방향을 대조한 뒤 연결합니다. 도식의 선 굵기는 전선 규격이 아닙니다.')+'</p><div class="warning-box">HOLD · 실제 단면/전류/케이블 길이와 접속 방식의 승인 전 결선하지 않습니다. 3D 경로는 간섭 검토용 추정입니다.</div><a class="button" href="'+(mode==='model'?'./wiring.html?wire=':'./index.html?wire=')+encodeURIComponent(w.id)+'">'+(mode==='model'?'배선도에서 이 연결 보기':'3D에서 이 하네스 보기')+' ↗</a><div class="divider"></div><h3>같은 NET의 연결</h3>'+relatedHTML(D.connections.filter(v=>v.net===w.net&&v.id!==w.id).slice(0,26));bindRelated(callback);return;}
  if(c){target.innerHTML='<div class="eyebrow">COMPONENT INSPECTOR / D3</div><div class="inspector-ref">'+esc(c.id)+'</div><h2>'+esc(c.name)+'</h2><p class="subtitle">'+esc(c.subtitle)+'</p><div class="divider"></div><div class="info-pair"><span>영역</span><strong>'+esc(groups[c.group]||c.group)+'</strong></div><div class="info-pair"><span>확정 상태</span><strong style="color:var(--amber)">'+(c.status==='hold'?'HOLD / 실물 검증 전':'연결 참조 / 검토 필요')+'</strong></div><p>'+esc(c.notes)+'</p>'+(c.delta?'<div class="warning-box">D3 변경 · '+esc(c.delta)+'</div>':'')+'<div class="divider"></div><h3>기능 단자 → NET</h3><p class="small">핀 표기가 없는 명칭은 기능 단자입니다. 부품 배치와 3D의 단자 위치는 실물 커넥터 핀 순서가 아닙니다.</p><div class="port-list">'+Object.entries(c.ports).map(([p,n])=>'<div class="port-row"><span>'+esc(p)+'</span><span>'+esc(n)+'</span></div>').join('')+'</div><a class="button" href="'+(mode==='model'?'./wiring.html?part=':'./index.html?part=')+encodeURIComponent(c.id)+'">'+(mode==='model'?'배선도에서 부품 보기':'3D에서 부품 보기')+' ↗</a><div class="divider"></div><h3>연결된 하네스</h3>'+relatedHTML(D.connections.filter(w=>w.from.startsWith(c.id+':')||w.to.startsWith(c.id+':')))+'<p class="small">근거 · '+c.source.map(esc).join(' / ')+'</p>';bindRelated(callback);return;}
  target.innerHTML='<div class="eyebrow">DESIGN STATUS / REVISION D3</div><div class="inspector-ref">SC / D3</div><h2>다중 센서 융합<br>사용자 추종형 스마트 카트</h2><p>부품과 선을 선택해 기능 단자, NET, 변경 사유를 확인하세요. 전륜 서보 2개, 전방 ToF와 전면 프레임 상단 LiDAR를 반영했습니다. 부품 배치와 회로 도식은 같은 결선 데이터를 사용합니다.</p><div class="divider"></div><div class="info-pair"><span>설계 전원</span><strong>24 V class</strong></div><div class="info-pair"><span>구동 모터</span><strong>250 W × 2</strong></div><div class="info-pair"><span>LiDAR 스캔 중심</span><strong>0.865 m 제안</strong></div><div class="info-pair"><span>추종 / 전방 센서</span><strong>UWB × 2 / ToF × 2</strong></div><div class="info-pair"><span>실물 제작 승인</span><strong style="color:var(--amber)">HOLD</strong></div><div class="warning-box">도면만으로 단락·발화·주행 안전을 보증할 수 없습니다. 부품 정격과 보호 협조, 회생, 제동을 확인한 뒤 제작 책임자가 승인해야 합니다.</div><button class="button" id="inspector-gates">12개 보류 조건 확인</button><div class="divider"></div><h3>이번 리비전의 핵심</h3><p>전륜 서보 전원·PWM 분리, 양쪽 킹핀·링크, 낮춘 LiDAR와 전방 ToF를 반영했습니다. 12V/20A는 컨버터 목표이며 실물 서보의 전압·핀맵·스톨 전류는 미확정입니다.</p>';
  $('#inspector-gates').onclick=gates;
 }
 document.addEventListener('click',e=>{if(e.target.closest('.gates-open')){e.preventDefault();gates()}if(e.target.closest('.sources-open')){e.preventDefault();sources()}const a=e.target.closest('a[download]');if(a?.getAttribute('href')?.endsWith('point-to-point.csv')){e.preventDefault();connectionCSV()}});
 document.addEventListener('keydown',e=>{if(!$('#modal-root').firstElementChild)return;if(e.key==='Escape')closeModal();if(e.key==='Tab'){const els=[...document.querySelectorAll('.modal button,.modal a,.modal input')],first=els[0],last=els.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}});
 return {D,$,esc,groups,kinds,colors,toast,save,csv,modal,gates,sources,inspect};
})();
