/* glTF 2.0 binary exporter for the assembled scene, with reference/net metadata. */
'use strict';
window.exportSmartCartGLB=function(builder){
 const gltf={asset:{version:'2.0',generator:'Smart Cart D2 procedural exporter',copyright:'Based on the user-owned JTech-CO/Smart-Cart visual reference; see source notice.'},scene:0,scenes:[{name:'Smart Cart D2 / ENGINEERING HOLD',nodes:[0]}],nodes:[{name:'Smart_Cart_D2',children:[],extras:{release:'HOLD',units:'metre',estimatedGeometry:true,scanCenterY:1.15,notFabricationCAD:true}}],meshes:[],materials:[],buffers:[{byteLength:0}],bufferViews:[],accessors:[],extras:{revision:'D2',note:'All envelopes and terminal positions are estimates. Harness IDs refer to data/design.json. Scene is assembled, not exploded.'}};
 const chunks=[],groups=new Map(),mats=new Map();let byteOffset=0;
 const linear=v=>v<=.04045?v/12.92:Math.pow((v+.055)/1.055,2.4);
 for(const it of builder.items){if(it.id==='FLOOR'||it.layer==='scan')continue;const vertices=new Float32Array(it.vertices),count=vertices.length/6;if(!count)continue;const key=JSON.stringify(it.mat);let mid=mats.get(key);if(mid===undefined){mid=gltf.materials.length;mats.set(key,mid);gltf.materials.push({name:'Material_'+mid,pbrMetallicRoughness:{baseColorFactor:[...it.mat.color.map(linear),it.mat.alpha],metallicFactor:it.mat.metal,roughnessFactor:it.mat.rough},doubleSided:true,alphaMode:it.mat.alpha<1?'BLEND':'OPAQUE',emissiveFactor:it.mat.color.map(v=>Math.min(1,v*it.mat.emissive))})}
  const min=[Infinity,Infinity,Infinity],max=[-Infinity,-Infinity,-Infinity];for(let i=0;i<vertices.length;i+=6)for(let j=0;j<3;j++){min[j]=Math.min(min[j],vertices[i+j]);max[j]=Math.max(max[j],vertices[i+j])}
  const vi=gltf.bufferViews.length;gltf.bufferViews.push({buffer:0,byteOffset,byteLength:vertices.byteLength,byteStride:24,target:34962});let pi=gltf.accessors.length;gltf.accessors.push({bufferView:vi,byteOffset:0,componentType:5126,count,type:'VEC3',min,max},{bufferView:vi,byteOffset:12,componentType:5126,count,type:'VEC3'});const primitive={attributes:{POSITION:pi,NORMAL:pi+1},material:mid,mode:4};if(!groups.has(it.id))groups.set(it.id,[]);groups.get(it.id).push(primitive);chunks.push(new Uint8Array(vertices.buffer));byteOffset+=vertices.byteLength;
 }
 for(const [id,primitives] of groups){const mi=gltf.meshes.length;gltf.meshes.push({name:id,primitives});const comp=window.CartDesign?.components.find(c=>c.id===id),wire=window.CartDesign?.connections.find(w=>w.id===id);gltf.nodes[0].children.push(gltf.nodes.length);gltf.nodes.push({name:id+(comp?' / '+comp.name:''),mesh:mi,extras:wire?{reference:id,from:wire.from,to:wire.to,net:wire.net,status:'HOLD',kind:wire.kind}:comp?{reference:id,functionalPorts:comp.ports,status:comp.status,notes:comp.notes}: {reference:id,estimatedGeometry:true}})}
 gltf.buffers[0].byteLength=byteOffset;const encoder=new TextEncoder(),json=encoder.encode(JSON.stringify(gltf)),jsonLength=Math.ceil(json.length/4)*4,binLength=Math.ceil(byteOffset/4)*4,total=12+8+jsonLength+8+binLength,out=new ArrayBuffer(total),view=new DataView(out),bytes=new Uint8Array(out);view.setUint32(0,0x46546c67,true);view.setUint32(4,2,true);view.setUint32(8,total,true);view.setUint32(12,jsonLength,true);view.setUint32(16,0x4e4f534a,true);bytes.fill(32,20,20+jsonLength);bytes.set(json,20);const p=20+jsonLength;view.setUint32(p,binLength,true);view.setUint32(p+4,0x004e4942,true);let off=p+8;for(const chunk of chunks){bytes.set(chunk,off);off+=chunk.length}return out;
};
if(typeof document!=='undefined')document.addEventListener('click',e=>{const a=e.target.closest('a[download]');if(a?.getAttribute('href')?.endsWith('.glb')&&window.cartBuilder){e.preventDefault();CartUI.toast('GLB 조립체를 생성합니다.');setTimeout(()=>{try{CartUI.save('Smart-Cart-D2.glb',exportSmartCartGLB(cartBuilder),'model/gltf-binary')}catch(err){CartUI.toast('GLB 생성 실패: '+err.message)}},30)}});
