'use strict';
(()=>{
 const {$,esc,D,inspect,save,toast,kinds}=CartUI,wrap=$('#drawing-wrap');let mode='physical',S=CartPictorial,sheet='power',selected='',vb=[0,0,1760,1000],svg,display,pointers=new Map(),start=null,moved=false;
 function updateView(){svg?.setAttribute('viewBox',vb.join(' '))}
 function setSheet(key){if(!S.defs[key])key='power';sheet=key;display=S.build(key);wrap.innerHTML=S.svg(key);svg=wrap.querySelector('svg');vb=[0,0,display.width,display.height];updateView();document.querySelectorAll('[data-sheet]').forEach(b=>b.classList.toggle('active',b.dataset.sheet===key));$('#sheet-caption').textContent=(mode==='physical'?'부품 / ':'도식 / ')+S.defs[key].title+' · '+(mode==='schematic'&&key==='overview'?'기능 요약':display.wires.length+'개 연결');applyFilters();wireEvents();highlight();}
 function applyFilters(){if(!svg)return;svg.querySelectorAll('.wire').forEach(g=>{g.style.display=g.dataset.kind==='return'&&!$('#returns-show').checked?'none':''});svg.querySelectorAll('.wire-id').forEach(t=>t.style.display=$('#wire-labels').checked?'block':'none')}
 function highlight(){applyFilters();svg?.querySelectorAll('.node').forEach(g=>g.classList.toggle('selected',g.dataset.node===selected));svg?.querySelectorAll('.wire').forEach(g=>{g.classList.toggle('selected',g.dataset.wire===selected);g.style.opacity=selected.startsWith('W')&&g.dataset.wire!==selected?'.28':'1';if(g.dataset.wire===selected){g.style.display='';g.querySelector('.wire-id').style.display='block'}})}
 function select(id,focus=false){if(!D.components.some(c=>c.id===id)&&!D.connections.some(w=>w.id===id))id='';selected=id;inspect(id,'wiring',id=>select(id,true));if(!id){highlight();return;}const target=S.findSheet(id);if(focus&&target!==sheet)setSheet(target);highlight();if(focus&&id.startsWith('W')&&display.paths[id]){const pts=display.paths[id],xs=pts.map(p=>p[0]),ys=pts.map(p=>p[1]);let x=Math.min(...xs),y=Math.min(...ys),w=Math.max(420,Math.max(...xs)-x),h=Math.max(350,Math.max(...ys)-y);vb=[x-100,y-100,w+200,h+200];updateView();}
  else if(focus){const n=display.nodes.find(n=>n.id===id);if(n){vb=[n.x-180,n.y-160,n.w+360,n.h+320];updateView()}}
 }
 function wireEvents(){svg.querySelectorAll('.node,.wire').forEach(g=>{g.addEventListener('click',e=>{if(moved)return;e.stopPropagation();select(g.dataset.node||g.dataset.wire)});g.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();select(g.dataset.node||g.dataset.wire)}})})}
 function zoom(f,cx=.5,cy=.5){const oldw=vb[2],oldh=vb[3],neww=Math.max(200,Math.min(display.width*2.8,oldw*f)),ratio=neww/oldw;vb=[vb[0]+oldw*cx*(1-ratio),vb[1]+oldh*cy*(1-ratio),neww,oldh*ratio];updateView()}
 function svgUnits(){const r=wrap.getBoundingClientRect(),scale=Math.max(vb[2]/r.width,vb[3]/r.height);return scale}
 wrap.addEventListener('wheel',e=>{e.preventDefault();const r=wrap.getBoundingClientRect();zoom(Math.exp(e.deltaY*.0013),(e.clientX-r.left)/r.width,(e.clientY-r.top)/r.height)},{passive:false});
 wrap.addEventListener('pointerdown',e=>{wrap.setPointerCapture(e.pointerId);pointers.set(e.pointerId,[e.clientX,e.clientY]);start=[e.clientX,e.clientY];moved=false;wrap.classList.add('dragging')});
 wrap.addEventListener('pointermove',e=>{if(!pointers.has(e.pointerId))return;let old=pointers.get(e.pointerId),dx=e.clientX-old[0],dy=e.clientY-old[1];if(start&&Math.hypot(e.clientX-start[0],e.clientY-start[1])>4)moved=true;if(pointers.size===2){let p=[...pointers.entries()].find(([id])=>id!==e.pointerId)[1],a=Math.hypot(old[0]-p[0],old[1]-p[1]),b=Math.hypot(e.clientX-p[0],e.clientY-p[1]);if(b>5)zoom(a/b)}else{const scale=svgUnits();vb[0]-=dx*scale;vb[1]-=dy*scale;updateView()}pointers.set(e.pointerId,[e.clientX,e.clientY])});
 const end=e=>{pointers.delete(e.pointerId);if(!pointers.size)wrap.classList.remove('dragging');if(!moved){const hit=document.elementFromPoint(e.clientX,e.clientY)?.closest('.node,.wire');if(hit)select(hit.dataset.node||hit.dataset.wire)}};wrap.addEventListener('pointerup',end);wrap.addEventListener('pointercancel',e=>{pointers.delete(e.pointerId);wrap.classList.remove('dragging')});
 wrap.addEventListener('keydown',e=>{if(e.target!==wrap)return;const step=vb[2]*.06;if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','+','=','-','Home','Escape'].includes(e.key))e.preventDefault();if(e.key==='ArrowLeft')vb[0]-=step;if(e.key==='ArrowRight')vb[0]+=step;if(e.key==='ArrowUp')vb[1]-=step;if(e.key==='ArrowDown')vb[1]+=step;if(e.key==='+'||e.key==='=')zoom(.8);if(e.key==='-')zoom(1.25);if(e.key==='Home')vb=[0,0,display.width,display.height];if(e.key==='Escape'){selected='';inspect('','wiring',id=>select(id,true));highlight();}updateView();});
 $('#zoom-in').onclick=()=>zoom(.75);$('#zoom-out').onclick=()=>zoom(1.333);$('#zoom-fit').onclick=()=>{vb=[0,0,display.width,display.height];updateView()};
 $('#wire-labels').onchange=()=>{applyFilters();highlight()};$('#returns-show').onchange=()=>{applyFilters();highlight()};
 document.querySelectorAll('[data-sheet]').forEach(b=>b.onclick=()=>{selected='';setSheet(b.dataset.sheet);inspect('','wiring',id=>select(id,true))});
 $('#svg-save').onclick=()=>{const copy=svg.cloneNode(true);copy.setAttribute('viewBox','0 0 '+display.width+' '+display.height);copy.setAttribute('width',display.width);copy.setAttribute('height',display.height);copy.querySelectorAll('.node.selected').forEach(g=>g.classList.remove('selected'));copy.querySelectorAll('.wire').forEach(g=>{g.style.opacity='1';g.classList.remove('selected');});save('Smart-Cart-D4-'+mode+'-'+sheet+'.svg','<?xml version="1.0" encoding="UTF-8"?>\n'+copy.outerHTML,'image/svg+xml;charset=utf-8')};
 function table(){const q=$('#wire-search').value.toLowerCase().trim(),kind=$('#wire-filter').value;const rows=D.connections.filter(w=>(kind==='all'||w.kind===kind)&&(!q||Object.values(w).join(' ').toLowerCase().includes(q)));$('#wire-table').innerHTML=rows.map(w=>'<tr><td><button data-select-wire="'+w.id+'">'+w.id+'</button></td><td>'+esc(w.from)+'</td><td>'+esc(w.to)+'</td><td><code>'+esc(w.net)+'</code><br><span class="muted">'+esc(kinds[w.kind])+'</span></td><td>'+esc(w.gauge)+'</td><td class="note">'+esc(w.note||'실물 단자·극성·규격 확인')+'</td><td><a href="./index.html?wire='+w.id+'">추적 ↗</a></td></tr>').join('')||'<tr><td colspan="7">검색 결과가 없습니다.</td></tr>';$('#wire-count').textContent=rows.length+' / '+D.connections.length;document.querySelectorAll('[data-select-wire]').forEach(b=>b.onclick=()=>{select(b.dataset.selectWire,true);wrap.scrollIntoView({block:'center',behavior:'smooth'})});}
 $('#wire-search').oninput=table;$('#wire-filter').onchange=table;
 const storageKey='smart-cart-d4-commission-v1';let record={};
 // Only accept known checklist IDs and primitive field types from local storage.
 try{const raw=JSON.parse(localStorage.getItem(storageKey)||'{}');if(raw&&typeof raw==='object'&&!Array.isArray(raw)){for(const c of D.checks){const v=raw[c.id];if(v&&typeof v==='object'&&!Array.isArray(v))record[c.id]={done:v.done===true,memo:typeof v.memo==='string'?v.memo:'',updated:typeof v.updated==='string'?v.updated:''};}}}catch(e){record={};}
 function persist(){try{localStorage.setItem(storageKey,JSON.stringify(record))}catch(e){toast('브라우저 저장을 사용할 수 없습니다. JSON으로 기록을 저장하세요.')}progress()}
 function progress(){let n=D.checks.filter(c=>record[c.id]?.done).length;$('#check-progress').textContent=n+' / '+D.checks.length+' 기록';$('#check-progress-bar').style.width=n/D.checks.length*100+'%';}
 function checks(){ $('#checks').innerHTML=D.checks.map(c=>'<article class="check-card"><label><input type="checkbox" data-check="'+c.id+'" '+(record[c.id]?.done?'checked':'')+'><span><span class="step">'+c.id+'</span>'+esc(c.title)+'</span></label><p>'+esc(c.detail)+'</p><textarea class="input" data-memo="'+c.id+'" placeholder="측정값 · 계측기 · 담당자 · 일시를 기록" aria-label="'+esc(c.title)+' 점검 메모">'+esc(record[c.id]?.memo||'')+'</textarea></article>').join('');document.querySelectorAll('[data-check]').forEach(el=>el.onchange=()=>{let id=el.dataset.check;record[id]={...record[id],done:el.checked,updated:new Date().toISOString()};persist()});document.querySelectorAll('[data-memo]').forEach(el=>el.oninput=()=>{let id=el.dataset.memo;record[id]={...record[id],memo:el.value,updated:new Date().toISOString()};persist()});progress();}
 $('#export-checks').onclick=()=>save('Smart-Cart-D4-inspection-record.json',JSON.stringify({revision:D.revision,exported:new Date().toISOString(),engineeringRelease:'HOLD',notice:'User-entered checklist only; not approval or physical test verification.',records:record,gates:D.gates},null,2),'application/json');
 $('#reset-checks').onclick=()=>{CartUI.modal('점검 기록 초기화','<p>이 브라우저에 저장한 체크와 메모를 삭제합니다. 이미 다운로드한 기록은 삭제되지 않습니다.</p><button id="confirm-reset" class="button">기록 삭제</button>');$('#confirm-reset').onclick=()=>{record={};persist();checks();$('#modal-close').click();toast('이 브라우저의 점검 기록을 초기화했습니다.')}};
 function setMode(value){mode=value==='schematic'?'schematic':'physical';S=mode==='physical'?CartPictorial:CartSchematic;document.querySelectorAll('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode));setSheet(sheet)}
 document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>setMode(b.dataset.mode));
 setSheet('power');inspect('','wiring',id=>select(id,true));table();checks();const params=new URLSearchParams(location.search);if(params.get('mode'))setMode(params.get('mode'));if(params.get('sheet'))setSheet(params.get('sheet'));if(params.get('wire')||params.get('part'))select(params.get('wire')||params.get('part'),true);
 window.wiringApp={select,setSheet,setMode,get mode(){return mode},get drawing(){return display},get sheet(){return sheet},get viewBox(){return vb},get selection(){return selected}};
})();
