#!/usr/bin/env python3
"""Regenerate JS and CSV mirrors from data/design.json (Python standard library)."""
from pathlib import Path
import csv,json,sys
ROOT=Path(__file__).resolve().parents[1]
def main():
    d=json.loads((ROOT/'data/design.json').read_text(encoding='utf-8'))
    (ROOT/'js/design-data.js').write_text("/* Single source: data/design.json. Generated by tools/sync_data.py. */\n'use strict';\nwindow.CartDesign = "+json.dumps(d,ensure_ascii=False,indent=2)+';\n',encoding='utf-8')
    def write(name,header,rows):
        with (ROOT/'data'/name).open('w',newline='',encoding='utf-8-sig') as f:
            w=csv.writer(f);w.writerow(header);w.writerows(rows)
    write('point-to-point.csv',['ID','From','To','Net','Kind','Sheet','Gauge','Status','Notes'],[[c.get(k,'') for k in ['id','from','to','net','kind','sheet','gauge','status','note']] for c in d['connections']])
    write('component-register.csv',['ID','Name','Subtitle','Kind','Group','Status','TerminalBasis','Notes','Sources'],[[c.get(k,'') for k in ['id','name','subtitle','kind','group','status','terminalBasis','notes']]+[' | '.join(c.get('source',[]))] for c in d['components']])
    write('terminal-register.csv',['Component','Terminal','Net'],[[c['id'],p,n] for c in d['components'] for p,n in c['ports'].items()])
    print(f"Generated {len(d['components'])} components, {len(d['connections'])} connections and {sum(len(c['ports']) for c in d['components'])} terminals.")
if __name__=='__main__':
    try:main()
    except (OSError,ValueError,KeyError) as e:print(f'ERROR: {e}',file=sys.stderr);sys.exit(1)
